import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { JSDOM } from 'jsdom';
import { launch } from './helpers.js';

function waitFor(window, check, timeout = 5000) {
  return new Promise((resolve, reject) => {
    if (check()) return resolve();
    const observer = new window.MutationObserver(() => { if (check()) { clearTimeout(timer); observer.disconnect(); resolve(); } });
    observer.observe(window.document, { subtree: true, childList: true, attributes: true, characterData: true });
    const timer = setTimeout(() => { observer.disconnect(); reject(new Error('UI condition not met')); }, timeout);
  });
}
test('editor DOM workflow against the real API', async t => {
  const directory = mkdtempSync(path.join(os.tmpdir(), 'northern-ui-'));
  const { child, url } = await launch(directory);
  const dom = new JSDOM(readFileSync('staff.html', 'utf8'), { url: `${url}/staff.html`, runScripts: 'outside-only' });
  const { window } = dom;
  let cookie = '';
  window.structuredClone = structuredClone;
  window.confirm = () => true;
  window.matchMedia = () => ({ matches: true });
  window.HTMLElement.prototype.scrollIntoView = () => {};
  window.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  window.HTMLDialogElement.prototype.close = function () { this.open = false; };
  window.fetch = async (route, options = {}) => {
    const response = await fetch(new URL(route, url), { ...options, headers: { ...options.headers, Cookie: cookie } });
    if (response.headers.get('set-cookie')) cookie = response.headers.get('set-cookie').split(';')[0];
    return response;
  };
  t.after(async () => { dom.window.close(); await new Promise(resolve => { child.once('exit', resolve); child.kill(); }); rmSync(directory, { recursive: true, force: true }); });
  window.eval(readFileSync('src/staff.js', 'utf8'));
  const $ = selector => window.document.querySelector(selector);
  await waitFor(window, () => !$('#demo-accounts').hidden);
  $('[data-demo="owner"]').click();
  await waitFor(window, () => !$('#editor-panel').hidden);
  assert.match($('#account-name').textContent, /Owner/);
  assert.equal($('#publish').hidden, false);
  $('#preview-hours').click();
  assert.equal($('#tab-hours').getAttribute('aria-selected'), 'true');
  $('#hours').value = 'Monday–Friday: 09:00–17:00';
  $('#hours').dispatchEvent(new window.Event('input', { bubbles: true }));
  assert.match($('#preview-hours').textContent, /09:00/);
  assert.match($('#changes').textContent, /09:00/);
  assert.equal($('#save').disabled, false);
  assert.equal($('#publish').disabled, true);
  $('#save').click();
  await waitFor(window, () => $('#message').textContent.includes('Draft saved'));
  assert.equal($('#publish').disabled, false);
  $('#publish').click();
  assert.equal($('#confirm-publish').open, true);
  $('#confirm-publish-button').click();
  await waitFor(window, () => $('#message').textContent.startsWith('Published.'));
  assert.match($('#history-list').textContent, /Restore to draft/);
  const publicContent = await (await fetch(`${url}/api/content`)).json();
  assert.equal(publicContent.hours, 'Monday–Friday: 09:00–17:00');
  $('#show-published').click();
  assert.equal($('#show-published').getAttribute('aria-pressed'), 'true');
  $('#logout').click();
  await waitFor(window, () => !$('#login-panel').hidden);
  $('[data-demo="staff"]').click();
  await waitFor(window, () => !$('#editor-panel').hidden);
  assert.equal($('#publish').hidden, true);
  assert.equal($('#history-list button'), null);
  $('#tab-announcement').click();
  $('#notice-text').value = '<img src=x onerror=alert(1)>';
  $('#notice-text').dispatchEvent(new window.Event('input', { bubbles: true }));
  $('#notice-visible').checked = true;
  $('#notice-visible').dispatchEvent(new window.Event('change', { bubbles: true }));
  $('#show-draft').click();
  assert.equal($('#preview-notice img'), null);
  assert.match($('#preview-notice').textContent, /<img src=x/);
  $('#save').click();
  await waitFor(window, () => $('#message').textContent.includes('Draft saved'));
  $('#submit-review').click();
  await waitFor(window, () => $('#status-badge').textContent === 'AWAITING REVIEW');
  assert.equal($('#submit-review').disabled, true);
});
