import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { launch } from './helpers.js';
import { appWindow, waitFor } from './dom-helpers.js';

test('shop and merchandise desk DOM workflows against the real API', async t => {
  const directory = mkdtempSync(path.join(os.tmpdir(), 'nl-shop-ui-'));
  const { child, url } = await launch(directory);
  const shop = appWindow('shop.html', 'src/shop.js', url);
  let staff;
  t.after(async () => { shop.dom.window.close(); staff?.dom.window.close(); await new Promise(resolve => { child.once('exit', resolve); child.kill(); }); rmSync(directory, { recursive: true, force: true }); });
  const { window, $ } = shop;
  await waitFor(window, () => $('#results-count').textContent === '4 designs');
  $('[data-category="prints"]').click(); assert.equal($('#results-count').textContent, '1 design'); assert.match($('#product-grid').textContent, /A Different Atmosphere/);
  $('[data-category="all"]').click(); $('#sort-products').value = 'price-asc'; $('#sort-products').dispatchEvent(new window.Event('change'));
  assert.equal($('#product-grid .product-meta h3').textContent, 'Orbit Sticker Set');
  $('#product-search').value = 'after dark'; $('#product-search').dispatchEvent(new window.Event('input')); assert.equal($('#results-count').textContent, '1 design');
  $('#product-grid .product-art').click(); assert.equal($('#product-dialog').open, true);
  $('#detail-option').value = 'M'; $('#detail-option').dispatchEvent(new window.Event('change')); $('#detail-add').click();
  assert.equal($('#cart-count').textContent, '1'); assert.equal(JSON.parse(window.localStorage.getItem('nl-merch-cart-v1'))[0].variant, 'M');
  $('#cart-button').click(); $('#checkout-button').click();
  await waitFor(window, () => $('#account-dialog').open);
  assert.equal($('#customer-name-label').hidden, false);
  $('#customer-name').value = 'UI Sample Guest'; $('#customer-email').value = 'ui-sample@example.com'; $('#customer-password').value = 'UITestPassword!123'; $('#customer-form').requestSubmit();
  await waitFor(window, () => $('#checkout-dialog').open);
  assert.equal($('#place-demo-order').disabled, true);
  $('#checkout-consent').checked = true; $('#checkout-consent').dispatchEvent(new window.Event('change')); $('#place-demo-order').click();
  await waitFor(window, () => $('#success-dialog').open);
  assert.match($('#order-confirmation').textContent, /NL-/); assert.equal($('#cart-count').textContent, '0');
  assert.equal(JSON.parse(window.localStorage.getItem('nl-merch-checkout-v1')), null);
  $('#view-orders').click(); await waitFor(window, () => Boolean($('#customer-orders .customer-order')));
  assert.match($('#customer-orders').textContent, /After Dark Tee/);
  // A later, identical cart should produce a new order, not reuse the completed attempt key.
  window.document.querySelector('[data-close="account-dialog"]').click();
  $('#product-grid .product-art').click(); $('#detail-option').value = 'M'; $('#detail-option').dispatchEvent(new window.Event('change')); $('#detail-add').click();
  $('#cart-button').click(); $('#checkout-button').click(); await waitFor(window, () => $('#checkout-dialog').open);
  $('#checkout-consent').checked = true; $('#checkout-consent').dispatchEvent(new window.Event('change')); $('#place-demo-order').click();
  await waitFor(window, () => $('#success-dialog').open);
  $('#view-orders').click(); await waitFor(window, () => window.document.querySelectorAll('#customer-orders .customer-order').length === 2);
  staff = appWindow('merch-admin.html', 'src/merch-admin.js', url);
  const admin = staff.$;
  await waitFor(staff.window, () => !admin('#demo-accounts').hidden);
  admin('[data-demo="staff"]').click(); await waitFor(staff.window, () => !admin('#merch-workspace').hidden);
  assert.equal(admin('#stat-orders').textContent, '2'); assert.equal(admin('#stat-designs').textContent, '4');
  assert.match(admin('#merch-orders').textContent, /UI Sample Guest/);
  admin('#inventory-list .visibility-button').click(); await waitFor(staff.window, () => admin('#message').textContent.startsWith('Design hidden'));
  assert.equal(admin('#stat-visible').textContent, '3');
  admin('#inventory-list .visibility-button').click(); await waitFor(staff.window, () => admin('#message').textContent.startsWith('Design restored'));
  assert.equal(admin('#stat-visible').textContent, '4');
  admin('#inventory-list .secondary').click(); assert.equal(admin('#product-editor').open, true);
  admin('#edit-price').value = '379.00'; admin('#product-form').requestSubmit();
  await waitFor(staff.window, () => !admin('#product-editor').open);
  await waitFor(staff.window, () => admin('#inventory-list').textContent.includes('379'));
  assert.equal((await (await fetch(`${url}/api/shop/catalog`)).json()).products[0].priceCents, 37900);
  const cancelButton = [...staff.window.document.querySelectorAll('#merch-orders button')].find(button => button.textContent === 'Cancel & restock');
  cancelButton.click(); await waitFor(staff.window, () => admin('#merch-orders').textContent.includes('CANCELLED'));
  // Orders retain their original snapshot even when the catalog's price changes.
  const liveOrders = [...staff.window.document.querySelectorAll('.merch-order-footer strong')].map(node => node.textContent); assert.ok(liveOrders.every(text => text.includes('349')));
});
