// Original demonstration merchandise. Not verified inventory, prices, or fulfilment offers.
export const sampleProducts = [
  { id: 'after-dark-tee', name: 'After Dark Tee', category: 'apparel', art: 'tee', priceCents: 34900, description: 'A black everyday tee with an understated Northern Lights wordmark. Original merchandise concept; fabric, sizing, and production specifications are not yet confirmed.', variants: [{ label: 'S', stock: 8 }, { label: 'M', stock: 12 }, { label: 'L', stock: 10 }, { label: 'XL', stock: 6 }], hidden: false, revision: 1 },
  { id: 'night-shift-hoodie', name: 'Night Shift Hoodie', category: 'apparel', art: 'hoodie', priceCents: 74900, description: 'An oversized silhouette imagined in forest green, with a small white chest mark. Sample design only; final garment details will be approved before any real sale.', variants: [{ label: 'S', stock: 5 }, { label: 'M', stock: 8 }, { label: 'L', stock: 7 }, { label: 'XL', stock: 4 }], hidden: false, revision: 1 },
  { id: 'aurora-print', name: 'A Different Atmosphere', category: 'prints', art: 'print', priceCents: 19900, description: 'An original aurora-inspired graphic print for your walls. A3 is a proposed format; paper, framing, and print specifications are not yet confirmed. Frame shown is illustrative.', variants: [{ label: 'A3 concept', stock: 20 }], hidden: false, revision: 1 },
  { id: 'orbit-sticker-set', name: 'Orbit Sticker Set', category: 'stickers', art: 'stickers', priceCents: 5900, description: 'Three Northern Lights graphic sticker concepts: the wordmark, orbit, and starburst. Sample artwork only; dimensions and materials remain to be confirmed.', variants: [{ label: 'Set of 3', stock: 30 }], hidden: false, revision: 1 },
];
export const categories = { apparel: 'Apparel', prints: 'Art prints', stickers: 'Stickers' };
export const money = cents => new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 2 }).format(cents / 100);
